CREATE TABLE usuarios
(

    id SERIAL PRIMARY KEY,

    nombre VARCHAR(100) NOT NULL,

    apellido VARCHAR(100) NOT NULL,

    email VARCHAR(255) UNIQUE NOT NULL,

    telefono VARCHAR(20),

    cedula VARCHAR(20) UNIQUE,

    password VARCHAR(255) NOT NULL,

    rol VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);